algoritmo "Estruturas de repetição CONTE ATE 10"
var
   contador: Inteiro
inicio
     contador <- 0
     Enquanto (contador <= 10) faca
              Escreval (contador)
              contador <- contador + 1
     FimEnquanto
     Escreval ("Terminei de contar")

fimalgoritmo

// Ex:         mao <- 0
// SINTAXE    Enquanto (mao <= 5) faca
//              troca
//              mao <- mao + 1
//            FimEnquanto