algoritmo "Dois Números"
var
     N1, N2, S: inteiro
     //N1 e N2 são os números a serem escolhidos//
     //S para guardar a soma dos numeros escolhidos

     
inicio

      Escreva ("informe um numero: ")
      Leia (N1)
      Escreva ("informe outro numero: ")
      Leia (N2)
      
      S <- N1+N2  //S recebe N1 + N2
      Escreva ("A soma entre ", N1, " e ", N2, " é igual a: ", S)

fimalgoritmo

// "<-" comando de atribuição (recebe)

